apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y63ken1yk-go
  janus-idp.io/tekton: y63ken1yk-go
  backstage.io/kubernetes-id: y63ken1yk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y63ken1yk-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
